/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.fhir2avro.util.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JellyBeanV4 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JellyBeanV4\",\"namespace\":\"com.fhir2avro.util.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"size\",\"type\":{\"type\":\"enum\",\"name\":\"Size\",\"symbols\":[\"UNKNOWN\",\"SMALL\",\"MEDIUM\",\"LARGE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int id;
  @Deprecated public com.fhir2avro.util.avro.Size size;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public JellyBeanV4() {}

  /**
   * All-args constructor.
   */
  public JellyBeanV4(java.lang.CharSequence name, java.lang.Integer id, com.fhir2avro.util.avro.Size size) {
    this.name = name;
    this.id = id;
    this.size = size;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return size;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.Integer)value$; break;
    case 2: size = (com.fhir2avro.util.avro.Size)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'size' field.
   */
  public com.fhir2avro.util.avro.Size getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(com.fhir2avro.util.avro.Size value) {
    this.size = value;
  }

  /** Creates a new JellyBeanV4 RecordBuilder */
  public static com.fhir2avro.util.avro.JellyBeanV4.Builder newBuilder() {
    return new com.fhir2avro.util.avro.JellyBeanV4.Builder();
  }
  
  /** Creates a new JellyBeanV4 RecordBuilder by copying an existing Builder */
  public static com.fhir2avro.util.avro.JellyBeanV4.Builder newBuilder(com.fhir2avro.util.avro.JellyBeanV4.Builder other) {
    return new com.fhir2avro.util.avro.JellyBeanV4.Builder(other);
  }
  
  /** Creates a new JellyBeanV4 RecordBuilder by copying an existing JellyBeanV4 instance */
  public static com.fhir2avro.util.avro.JellyBeanV4.Builder newBuilder(com.fhir2avro.util.avro.JellyBeanV4 other) {
    return new com.fhir2avro.util.avro.JellyBeanV4.Builder(other);
  }
  
  /**
   * RecordBuilder for JellyBeanV4 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JellyBeanV4>
    implements org.apache.avro.data.RecordBuilder<JellyBeanV4> {

    private java.lang.CharSequence name;
    private int id;
    private com.fhir2avro.util.avro.Size size;

    /** Creates a new Builder */
    private Builder() {
      super(com.fhir2avro.util.avro.JellyBeanV4.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.fhir2avro.util.avro.JellyBeanV4.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.size)) {
        this.size = data().deepCopy(fields()[2].schema(), other.size);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing JellyBeanV4 instance */
    private Builder(com.fhir2avro.util.avro.JellyBeanV4 other) {
            super(com.fhir2avro.util.avro.JellyBeanV4.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.size)) {
        this.size = data().deepCopy(fields()[2].schema(), other.size);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder setId(int value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'size' field */
    public com.fhir2avro.util.avro.Size getSize() {
      return size;
    }
    
    /** Sets the value of the 'size' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder setSize(com.fhir2avro.util.avro.Size value) {
      validate(fields()[2], value);
      this.size = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'size' field has been set */
    public boolean hasSize() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'size' field */
    public com.fhir2avro.util.avro.JellyBeanV4.Builder clearSize() {
      size = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public JellyBeanV4 build() {
      try {
        JellyBeanV4 record = new JellyBeanV4();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Integer) defaultValue(fields()[1]);
        record.size = fieldSetFlags()[2] ? this.size : (com.fhir2avro.util.avro.Size) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
