/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.fhir2avro.util.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JellyBeanV6 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JellyBeanV6\",\"namespace\":\"com.fhir2avro.util.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"texture\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence texture;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public JellyBeanV6() {}

  /**
   * All-args constructor.
   */
  public JellyBeanV6(java.lang.CharSequence name, java.lang.Integer id, java.lang.CharSequence texture) {
    this.name = name;
    this.id = id;
    this.texture = texture;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return texture;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.Integer)value$; break;
    case 2: texture = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'texture' field.
   */
  public java.lang.CharSequence getTexture() {
    return texture;
  }

  /**
   * Sets the value of the 'texture' field.
   * @param value the value to set.
   */
  public void setTexture(java.lang.CharSequence value) {
    this.texture = value;
  }

  /** Creates a new JellyBeanV6 RecordBuilder */
  public static com.fhir2avro.util.avro.JellyBeanV6.Builder newBuilder() {
    return new com.fhir2avro.util.avro.JellyBeanV6.Builder();
  }
  
  /** Creates a new JellyBeanV6 RecordBuilder by copying an existing Builder */
  public static com.fhir2avro.util.avro.JellyBeanV6.Builder newBuilder(com.fhir2avro.util.avro.JellyBeanV6.Builder other) {
    return new com.fhir2avro.util.avro.JellyBeanV6.Builder(other);
  }
  
  /** Creates a new JellyBeanV6 RecordBuilder by copying an existing JellyBeanV6 instance */
  public static com.fhir2avro.util.avro.JellyBeanV6.Builder newBuilder(com.fhir2avro.util.avro.JellyBeanV6 other) {
    return new com.fhir2avro.util.avro.JellyBeanV6.Builder(other);
  }
  
  /**
   * RecordBuilder for JellyBeanV6 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JellyBeanV6>
    implements org.apache.avro.data.RecordBuilder<JellyBeanV6> {

    private java.lang.CharSequence name;
    private int id;
    private java.lang.CharSequence texture;

    /** Creates a new Builder */
    private Builder() {
      super(com.fhir2avro.util.avro.JellyBeanV6.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.fhir2avro.util.avro.JellyBeanV6.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.texture)) {
        this.texture = data().deepCopy(fields()[2].schema(), other.texture);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing JellyBeanV6 instance */
    private Builder(com.fhir2avro.util.avro.JellyBeanV6 other) {
            super(com.fhir2avro.util.avro.JellyBeanV6.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.texture)) {
        this.texture = data().deepCopy(fields()[2].schema(), other.texture);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder setId(int value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder clearId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'texture' field */
    public java.lang.CharSequence getTexture() {
      return texture;
    }
    
    /** Sets the value of the 'texture' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder setTexture(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.texture = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'texture' field has been set */
    public boolean hasTexture() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'texture' field */
    public com.fhir2avro.util.avro.JellyBeanV6.Builder clearTexture() {
      texture = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public JellyBeanV6 build() {
      try {
        JellyBeanV6 record = new JellyBeanV6();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Integer) defaultValue(fields()[1]);
        record.texture = fieldSetFlags()[2] ? this.texture : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
