/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.fhir2avro.util.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Size { 
  UNKNOWN, SMALL, MEDIUM, LARGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Size\",\"namespace\":\"com.fhir2avro.util.avro\",\"symbols\":[\"UNKNOWN\",\"SMALL\",\"MEDIUM\",\"LARGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
