/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.fhir2avro.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FacebookSpecialUser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FacebookSpecialUser\",\"namespace\":\"com.fhir2avro.avro\",\"fields\":[{\"name\":\"user\",\"type\":{\"type\":\"record\",\"name\":\"FacebookUser\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]},{\"name\":\"num_likes\",\"type\":\"int\"},{\"name\":\"num_photos\",\"type\":\"int\"},{\"name\":\"num_groups\",\"type\":\"int\"}]}},{\"name\":\"specialData\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public com.fhir2avro.avro.FacebookUser user;
  @Deprecated public int specialData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public FacebookSpecialUser() {}

  /**
   * All-args constructor.
   */
  public FacebookSpecialUser(com.fhir2avro.avro.FacebookUser user, java.lang.Integer specialData) {
    this.user = user;
    this.specialData = specialData;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user;
    case 1: return specialData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user = (com.fhir2avro.avro.FacebookUser)value$; break;
    case 1: specialData = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'user' field.
   */
  public com.fhir2avro.avro.FacebookUser getUser() {
    return user;
  }

  /**
   * Sets the value of the 'user' field.
   * @param value the value to set.
   */
  public void setUser(com.fhir2avro.avro.FacebookUser value) {
    this.user = value;
  }

  /**
   * Gets the value of the 'specialData' field.
   */
  public java.lang.Integer getSpecialData() {
    return specialData;
  }

  /**
   * Sets the value of the 'specialData' field.
   * @param value the value to set.
   */
  public void setSpecialData(java.lang.Integer value) {
    this.specialData = value;
  }

  /** Creates a new FacebookSpecialUser RecordBuilder */
  public static com.fhir2avro.avro.FacebookSpecialUser.Builder newBuilder() {
    return new com.fhir2avro.avro.FacebookSpecialUser.Builder();
  }
  
  /** Creates a new FacebookSpecialUser RecordBuilder by copying an existing Builder */
  public static com.fhir2avro.avro.FacebookSpecialUser.Builder newBuilder(com.fhir2avro.avro.FacebookSpecialUser.Builder other) {
    return new com.fhir2avro.avro.FacebookSpecialUser.Builder(other);
  }
  
  /** Creates a new FacebookSpecialUser RecordBuilder by copying an existing FacebookSpecialUser instance */
  public static com.fhir2avro.avro.FacebookSpecialUser.Builder newBuilder(com.fhir2avro.avro.FacebookSpecialUser other) {
    return new com.fhir2avro.avro.FacebookSpecialUser.Builder(other);
  }
  
  /**
   * RecordBuilder for FacebookSpecialUser instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FacebookSpecialUser>
    implements org.apache.avro.data.RecordBuilder<FacebookSpecialUser> {

    private com.fhir2avro.avro.FacebookUser user;
    private int specialData;

    /** Creates a new Builder */
    private Builder() {
      super(com.fhir2avro.avro.FacebookSpecialUser.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.fhir2avro.avro.FacebookSpecialUser.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user)) {
        this.user = data().deepCopy(fields()[0].schema(), other.user);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.specialData)) {
        this.specialData = data().deepCopy(fields()[1].schema(), other.specialData);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing FacebookSpecialUser instance */
    private Builder(com.fhir2avro.avro.FacebookSpecialUser other) {
            super(com.fhir2avro.avro.FacebookSpecialUser.SCHEMA$);
      if (isValidValue(fields()[0], other.user)) {
        this.user = data().deepCopy(fields()[0].schema(), other.user);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.specialData)) {
        this.specialData = data().deepCopy(fields()[1].schema(), other.specialData);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'user' field */
    public com.fhir2avro.avro.FacebookUser getUser() {
      return user;
    }
    
    /** Sets the value of the 'user' field */
    public com.fhir2avro.avro.FacebookSpecialUser.Builder setUser(com.fhir2avro.avro.FacebookUser value) {
      validate(fields()[0], value);
      this.user = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'user' field has been set */
    public boolean hasUser() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'user' field */
    public com.fhir2avro.avro.FacebookSpecialUser.Builder clearUser() {
      user = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'specialData' field */
    public java.lang.Integer getSpecialData() {
      return specialData;
    }
    
    /** Sets the value of the 'specialData' field */
    public com.fhir2avro.avro.FacebookSpecialUser.Builder setSpecialData(int value) {
      validate(fields()[1], value);
      this.specialData = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'specialData' field has been set */
    public boolean hasSpecialData() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'specialData' field */
    public com.fhir2avro.avro.FacebookSpecialUser.Builder clearSpecialData() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public FacebookSpecialUser build() {
      try {
        FacebookSpecialUser record = new FacebookSpecialUser();
        record.user = fieldSetFlags()[0] ? this.user : (com.fhir2avro.avro.FacebookUser) defaultValue(fields()[0]);
        record.specialData = fieldSetFlags()[1] ? this.specialData : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
